obj-$(CONFIG_MSM_HOTPLUG) 	+= msm_hotplug.o
obj-$(CONFIG_BRICKED_HOTPLUG) 	+= bricked_hotplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) 	+= alucard_hotplug.o
obj-$(CONFIG_INTELLI_PLUG) 	+= intelli_plug.o
obj-$(CONFIG_ASMP)		+= autosmp.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o 
obj-$(CONFIG_CLUSTER_PLUG)	+= cluster_plug.o
obj-$(CONFIG_LAZYPLUG)		+= lazyplug.o
CFLAGS_lazyplug.o		+= -finline-functions

obj-$(CONFIG_MSM_SLEEPER) 	+= msm_sleeper.o


